#%RAML 1.0 NamedExample

  [
  {
    "segment110": {
      "Record ID": "110",
      "Record Length": "0028",
      "Report Date": "032020",
      "Report Time": "162336",
      "Preamble": "TNV1",
      "vNumber": "07",
      "wordLenght": "00",
      "wordText": null
    }
  },
  {
    "segment357": {
      "Record ID": "357",
      "Record Length": "0170",
      "SPECIAL_COMMENT_CODE_RECORD": "  P",
      "EVALUATION_RECORD": "04",
      "DATE_OPENED_RECORD": "1309",
      "STATUS_DATE_RECORD": "19  ",
      "CONSUMER_COMMENT_LENGTH_RECORD": "0001",
      "CONSUMER_COMMENT_TEXT": " B2147900000000B429BCCCCCCCCCCCC------------B6311662272HF16SYNCB/HANOVERDIRF3160919051107  ",
      "B2subseg": {
        "B2subsegIndicator": "B2",
        "B2subsegLenght": "14",
        "monthsReviewed": "79",
        "30DayCounter": "00"
      }
    }
  },
  {
    "segment357": {
      "Record ID": "357",
      "Record Length": "0164",
      "SPECIAL_COMMENT_CODE_RECORD": "19N",
      "EVALUATION_RECORD": "02",
      "DATE_OPENED_RECORD": "1605",
      "STATUS_DATE_RECORD": "18  ",
      "CONSUMER_COMMENT_LENGTH_RECORD": "0001",
      "CONSUMER_COMMENT_TEXT": " B2142800000000B429B000000000000000000000000B6252240355BC10GE CARD COF3160518A3111819",
      "B2subseg": {
        "B2subsegIndicator": "B2",
        "B2subsegLenght": "14",
        "monthsReviewed": "28",
        "30DayCounter": "00"
      }
    }
  },
  {
    "segment357": {
      "Record ID": "357",
      "Record Length": "0178",
      "SPECIAL_COMMENT_CODE_RECORD": "19N",
      "EVALUATION_RECORD": "06",
      "DATE_OPENED_RECORD": "1408",
      "STATUS_DATE_RECORD": "16  ",
      "CONSUMER_COMMENT_LENGTH_RECORD": "0001",
      "CONSUMER_COMMENT_TEXT": " B2142800000000B429B00CCCCCCCCCCCCCCCCCCC-CCB520          062516B6191260847BC04CITIF3160816A3111819",
      "B2subseg": {
        "B2subsegIndicator": "B2",
        "B2subsegLenght": "14",
        "monthsReviewed": "28",
        "30DayCounter": "00"
      }
    }
  },
  {
    "segment357": {
      "Record ID": "357",
      "Record Length": "0158",
      "SPECIAL_COMMENT_CODE_RECORD": "18N",
      "EVALUATION_RECORD": "02",
      "DATE_OPENED_RECORD": "1603",
      "STATUS_DATE_RECORD": "19  ",
      "CONSUMER_COMMENT_LENGTH_RECORD": "0001",
      "CONSUMER_COMMENT_TEXT": " B2141900000000B423B000000000000000000B6253205140BC10BK OF AMERF3160319A2111818",
      "B2subseg": {
        "B2subsegIndicator": "B2",
        "B2subsegLenght": "14",
        "monthsReviewed": "19",
        "30DayCounter": "00"
      }
    }
  },
  {
    "segment357": {
      "Record ID": "357",
      "Record Length": "0170",
      "SPECIAL_COMMENT_CODE_RECORD": "19N",
      "EVALUATION_RECORD": "02",
      "DATE_OPENED_RECORD": "1211",
      "STATUS_DATE_RECORD": "17  ",
      "CONSUMER_COMMENT_LENGTH_RECORD": "0001",
      "CONSUMER_COMMENT_TEXT": " B2146900000000B429BCCCCCCCCCCCCCCCCCCCCCCCCB6311290138BC16BANK CREDIT CARDF3161117A2111819",
      "B2subseg": {
        "B2subsegIndicator": "B2",
        "B2subsegLenght": "14",
        "monthsReviewed": "69",
        "30DayCounter": "00"
      }
    }
  },
  {
    "segment357": {
      "Record ID": "357",
      "Record Length": "0172",
      "SPECIAL_COMMENT_CODE_RECORD": "  P",
      "EVALUATION_RECORD": "03",
      "DATE_OPENED_RECORD": "1409",
      "STATUS_DATE_RECORD": "15  ",
      "CONSUMER_COMMENT_LENGTH_RECORD": "0001",
      "CONSUMER_COMMENT_TEXT": " A92134764523902AC6A84B2141900000000B405BB6362990515EZ21USA SERVICING COMPANYF3160915A21112  ",
      "A9subseg": {
        "A9subsegIndicator": "A9",
        "A9subsegLenght": "21",
        "accountNumber": "34764523902AC6A84B2141900000000B405BB6362990515EZ21USA SERVICING COMPANYF3160915A21112  "
      }
    }
  }
]